version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "avano"
    reviewers:
      - "avano"
    open-pull-requests-limit: 10
