name: Sync BOM
on:
  push:
    branches:
      - main

jobs:
  sync-bom:
    name: Sync BOM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Init Git info
        run: |
          git config --global user.email "actions@workflow.github.com"
          git config --global user.name "GitHub Actions"
      - name: Sync BOM
        run: |
          mvn --no-transfer-progress --activate-profiles update-bom clean install

          if [ -n "$(git status --porcelain)" ]; then
            git commit --all --message "[BOM] Sync BOM"
            git push origin main
          fi

